name: Travis
favicon: null
layout_spectrum: 0.48695
typography_spectrum: 0.06227169465273619
title: Travis DeMeester
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.1875
  lightness: 0.19877522415481508
  saturation: 0.2842965782620013
  rhythmicContrast: 0.8756023768801242
purpose: []
