name: Travis
favicon: null
layout_spectrum: 0.74161
typography_spectrum: 0.69225
title: 'Designing the future of Tech, Energy, National Security, and Advanced Manufacturing'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0d0b0c'
    - '#7f9f5c'
    - '#415063'
    - '#ff754f'
  brandStrength: 0.75
  lightness: 0.9375
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
