name: Travis
favicon: null
layout_spectrum: 0.70751
typography_spectrum: 0.8337
title: Travis DeMeester
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0d0b0c'
    - '#7f9f5c'
    - '#415063'
    - '#ff754f'
  brandStrength: 0.5
  lightness: 0.19877522415481508
  saturation: 0.2842965782620013
  rhythmicContrast: 0.8756023768801242
purpose: []
