name: Travis DeMeester
favicon: null
layout_spectrum: 0.47166
typography_spectrum: 0.69225
title: 'Designing the future of Tech, Energy, National Security, and Advanced Manufacturing'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7a41a'
    - '#001547'
    - '#275d79'
    - '#ffef38'
    - '#8facbe'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
